# Projecticum

To prove I'm able to use bibliography applications like "Zotero", a small introduction to my current projecticum will be written, and a bibliography will be automaticall generated using Zotero.

&nbsp;

Projecticum "Liquid biopsies sequencing analysis project"

&nbsp;

For projecticum "Liquid biospies", a collaboration between the Princes Maxima Centre for childoncology and the unniversity of applied sciences Utrecht, the data analysis of Neuroblastomia and the comparisson of tumor-biopsy sequencing data and cell-free sequencing data was central.

Neuroblastomia is a form of cancer formed by cells derived from the neural crest, tumors can be generated in any part of the sympathetic neural system. Because of their origin in developing tissues, neuroblastomas mostly occur in young children, the median age being 17 months old. Symptoms vary based on location of the tumor: they usually appear upon adrenal medulla or the paraspinal ganglia, but they can also appear upon the liver or in bone marrow (1). Neuroblastoma is distinct from other tumor due to their range of clinical behaviour. In some patiënts the disease can spontaneously regress, in others the disease is metastatic and highly-aggressive (2). Patiënts with neuroblastoma can be assigned a pre-treatment risk classification: either low, intermediate, or high-risk (3). These risk levels are based on histological data (3), but also on specific genomic mutations found during tumor biopsy sequencing (2).

The use of genomic information in the prognosis of neuroblastoma risk classification looks at multiple factors: upregulation of the _MYCN_ proto-oncogene (defined as more than 10 copies of the gene) can be found in 20% of overall cases and generally carries a poor prognosis (2). Furthermore, loss-of-function in chromosomes 1p36 (4) and 11q (5) or gain of function at chromosome 17q (6) is also frequently seen in aggressive cases of neuroblastoma. Using these genomic markers can thus be used to predict the severity of the disease in patiënts. However, currently, in order to perform an genomic analysis a tumor biopsy needs to be performed. These biopsies risk complications for the patiënts due to the general young nature of the patiënt, risking problems with anesthesia, excess bleeding, infections or other cimplications (8).

Liquid biopsies, the subject of this project, might be able to alievate some of the pressure off of tumor biospies. Blood samples from leukoblastomia patiënts contain circulating tumor cells, which can be studied via genomics/proteomics techniques. This is particularly helpful for leukoblastomia patiënts where tumor cells are not available from the main tumor, or where these are not sufficient for a genomics study. Due to the higher amount of circulating cell-free DNA, liquid biospies might prove to be a way to monitor the progression of disease in neuroblastomia patiënts while performing a smaller amount of invase surgeries. (9). In order for liquid biopsies to be used as a monitoring technique next to tumor biopsies, however, it needs to be proven that liquid biopsy genetic profiles mirror the genetic profiles of tumor biopsies. Although there has been research into this matter (10), it is not yet been proven to the point where it is part of routine diagnostic pipelines.  

Herein lies the question for project liquid biopsies. The princess maxima centre has recently set up a whole exome sequencing (WES) for liquid biospies of neuroblastomia patiënts, the same WES pipeline used for sequencing of cfDNA. Having the same pipeline allows them to compare the sequencing datasets of the patiënts to determine whether all aberrations found in tumor biopsy are also found in liquid biopsy. Furthermore, this allows them to study the heterogenicity of the tumor by the identification of abberations that are present in the liquid biopsy, but not in the tumor biopsy. However, this comparisson of the tumor and liquid biopsies is currently done manually, a labourous and time-consuming process. Thus, the assignment for this project is simple: using programming langauges, automate the comparisson of WES data of tumor and liquid biopsies. 



(1) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3306838/
(2) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4418018/
(3) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2650389/
(4) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC41727/
(5) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5492892/
(6) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2362984/
(7) https://pubmed.ncbi.nlm.nih.gov/28142287/
(8) https://www.cancer.org/cancer/neuroblastoma/detection-diagnosis-staging/how-diagnosed.html
(9) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5299732/
(10) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4567134/


PLAN:
 - Intro
 - Part about neuroblastoma
 - Part about tumor biopsies
 - Part about cell-free DNA
 - Part about CNV's