# R Packages

To prove my ability to create a package based on previous code, a set of functions will be created based on the "pokemon" dataset previously used will be created, and these functions will be transformed into a package.

First of, the pokemon package, supplied from "Rounak Banik" on [kaggle](https://www.kaggle.com/datasets/rounakbanik/pokemon), will be loaded in

```{r 009_dependancies}
library(tidyverse)
library(here)
```

```{r}
pokemon<-read_csv("data/pokemon.csv") %>% select(name,abilities:japanese_name,percentage_male:is_legendary)

pokemon[1,] %>% select(name, type1, type2, abilities:is_legendary)

pokemon_type<-function(x,y){
  A<-pokemon[pokemon$name==x,]
  B<-pokemon[pokemon$name==y,]
  AB<-full_join(A, B)
  #########################
  if(is.na(pokemon$type2[pokemon$name==x])){
    mes1<-paste0(pokemon$name[pokemon$name==x], " is a ", pokemon$type1[pokemon$name==x], " type")
  } else {
    mes1<-paste0(pokemon$name[pokemon$name==x], " is a ", pokemon$type1[pokemon$name==x], " and a ", pokemon$type2[pokemon$name==x], " type")
  }
  
  ###########################3
  if(is.na(pokemon$type2[pokemon$name==y])){
    mes2<-paste0(pokemon$name[pokemon$name==y], " is a ", pokemon$type1[pokemon$name==y], " type")
  } else {
    mes2<-paste0(pokemon$name[pokemon$name==y], " is a ", pokemon$type1[pokemon$name==y], " and a ", pokemon$type2[pokemon$name==y], " type")
  }
  print(mes1)
  print(mes2)
}

type_matchup("Drapion", "Chimchar")



```

