# Future endeavours

<body id="start">
<div class="topnav">
  <a href='index.html#Frontpage'>Frontpage</a>
  <a href='data-visualisation.html#data-visualisation'>Data visualisation</a>
  <a href='parametized-data-germany.html#parametized-data'>Parametizing data</a>
  <a href='directory-structure.html#directory-structure'>Directory structure</a>
  <a href='creating-a-r-package.html#creating-a-r-package'>R-package</a>
  <a href='sql.html#SQL'>SQL</a>
  <a href='bibliography-using-zotero.html#Bibliography using Zotero'>Zotero</a>
  <a href='open-reproductibility-analysis.html#open-reproductibility-analysis'>Reproductibility</a>
  <a class="active" href='future-endeavours.html#future-endeavours'>Future endeavours</a>
  <a href='free-research-project-index.html#free-research-project'> Free research (Machine learning)</a>
  <a href='cv.html#cv'>CV</a>
  <a href='bibliography.html#bibliography'>Bibliography</a>
</div>


&nbsp;

```{r setup_3, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

So, you might know who I am and what my skills are, but the question remains: What do I want? In which direction do I want to carve my future? Let me put my cards on the table for you.

__My main goal is to work within the field of microbiology__, specifically bacteriology. Ever since my specialisation in microbiology, bacteria have always been my passion, and although I enjoy working with parasites and virus' too (yet to work with fungi), bacteria do have a special place in my heart. How such tiny creatures create colonies big enough to be seen with the naked eye, how they're individually so simple yet can create disastrous infections together, I adore them.

However, I also do enjoy data sciences quite a bit. Thus, my best-case scenario would be to work in a microbiological lab, performing experiments on bacteria while also being able to __handle and visualise the data from my (or coworkers') experiments__. While performing some research into different data-sciences techniques performed in bacteriology, machine learning kept popping up it's head again and again, be it [for studying the microbiome](https://builtin.com/data-science/microbiome-research-data-science) or for  [the identification of bacterial colonies by computers](https://towardsdatascience.com/recognition-and-counting-of-microorganisms-on-petri-dishes-53a499283dc8). I was quite curious about how machine learning worked myself, and it seems like quite the important technique in microbiology, so I decided to spend some time to get a basic understanding of machine learning within microbiology.

Originally, I considered learning this techniques in python: This would, however, add an entire new section to my research where instead of immidiately studying machine learning, I'd have to study how python works before. This could be a research subject on it's own, so I decided on studying machine learning in R instead.

To prove that I'm able to learn new skills without any guidance, __I took the time of 4 days (32 hours) to try and learn the basics of machine learning techniques used in microbiology__. You can follow my journey through this research under "Free research (machine learning)"

